In [1]:
!pwd

/Users/ricardo/Desktop/book-da


# Capítulo 5 - Introdução ao Pandas

In [20]:
import pandas as pd
import numpy as np

In [3]:
#from pandas import Series, Dataframe

## 5.1 Estrutura de Dados do Pandas

### 5.1.1 SERIES

objeto = 1 x ( array unidimensional de dados ) + 1 x ( indice como array associado de rótulos) 

#### SÉRIES SIMPLES: 1 x ( array unidimensional de dados ) # sem array de rótulos

In [5]:
obj = pd.Series([4,7,-5,3])

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
type(obj)

pandas.core.series.Series

In [8]:
obj.values

array([ 4,  7, -5,  3])

In [10]:
obj.index

RangeIndex(start=0, stop=4, step=1)

#### SÉRIES: 1 x ( array unidimensional de dados ) + 1 x ( indice array de rótulos)

In [11]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])

In [12]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2.values

array([ 4,  7, -5,  3])

In [15]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

acessando dados em séries via label do índice

In [16]:
obj2['d']

4

In [18]:
obj2[0]  # também podemos acessar via ínice numérico

4

In [19]:
obj2[['d','b','c']]

d    4
b    7
c    3
dtype: int64

In [20]:
lista_indices = ['d','b','c']

In [21]:
obj2[lista_indices]

d    4
b    7
c    3
dtype: int64

In [22]:
obj2[obj2 > 3]

d    4
b    7
dtype: int64

In [27]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [30]:
import numpy as np

In [31]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

<b>Serie</b> é como se fosse um <b>dicionário ordenado</b>

In [36]:
'b' in obj2

True

In [37]:
'a' in obj2

True

In [38]:
'd' in obj2

True

Criando série de dicionário

In [52]:
dicionario = {'São Paulo': 1, 'Minas Gerais': 2, 'Rio de Janeiro':3, 'Rio Grando do Sul':4}

In [55]:
obj3 = pd.Series(dicionario)
obj3

São Paulo            1
Minas Gerais         2
Rio de Janeiro       3
Rio Grando do Sul    4
dtype: int64

In [67]:
lista_estados = list(obj3.index)
lista_estados

['São Paulo', 'Minas Gerais', 'Rio de Janeiro', 'Rio Grando do Sul']

In [74]:
lista_ordenada = ['Minas Gerais','Rio de Janeiro', 'Rio Grando do Sul','São Paulo']

Reordenando a série pelos labels

In [77]:
obj4 = pd.Series(obj3, lista_ordenada)
obj4

Minas Gerais         2
Rio de Janeiro       3
Rio Grando do Sul    4
São Paulo            1
dtype: int64

In [78]:
obj5 = pd.Series(obj4, ['São Paulo', 'Sergipe','Minas Gerais'])
obj5

São Paulo       1.0
Sergipe         NaN
Minas Gerais    2.0
dtype: float64

São Paulo já existia</br>
Sergipe não existia e foi inserido sem valor</br>
Minas gerais já existia, foi mantido e reposicioado<br>
Rio Grande do Sul e Rio de Janeiro foram excluídos, pois não estão na nova lista de chaves</br>

In [80]:
pd.isnull(obj5)

São Paulo       False
Sergipe          True
Minas Gerais    False
dtype: bool

In [81]:
pd.notnull(obj5)

São Paulo        True
Sergipe         False
Minas Gerais     True
dtype: bool

#### Nomeando o array indice e o array de valores da serie

In [83]:
obj5.name = "Estado"

In [84]:
obj5

São Paulo       1.0
Sergipe         NaN
Minas Gerais    2.0
Name: Estado, dtype: float64

In [85]:
obj5.index.name = 'state'

In [86]:
obj5

state
São Paulo       1.0
Sergipe         NaN
Minas Gerais    2.0
Name: Estado, dtype: float64

In [89]:
obj5.name

'Estado'

### 5.1.2 DataFrame

#### Operações entre Dataframes e Series

In [3]:
import numpy as np

In [8]:
arr = np.arange(12.).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [9]:
arr[0]

array([0., 1., 2., 3.])

In [10]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [12]:
array2 = np.arange(12).reshape(3,4)
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Ordenação e classificação

In [22]:
obj = pd.Series(range(4), index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [25]:
frame  = pd.DataFrame(np.arange(8).reshape((2,4)), index=['three','one'], columns=['d','a','b','c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [26]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [30]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [31]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [34]:
obj = pd.Series([4,7,-3,2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [38]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

valor indicativo de ausencia de valor será ordenado no final da série

In [39]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [42]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [43]:
obj.sort_values(ascending=False)

2    7.0
0    4.0
5    2.0
4   -3.0
1    NaN
3    NaN
dtype: float64

In [46]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [51]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [52]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [57]:
frame = frame[['a','b']]
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [59]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [62]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [63]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [65]:
help(pd.Series.rank)

Help on function rank in module pandas.core.generic:

rank(self: 'FrameOrSeries', axis=0, method: 'str' = 'average', numeric_only: 'Optional[bool_t]' = None, na_option: 'str' = 'keep', ascending: 'bool_t' = True, pct: 'bool_t' = False) -> 'FrameOrSeries'
    Compute numerical data ranks (1 through n) along axis.
    
    By default, equal values are assigned a rank that is the average of the
    ranks of those values.
    
    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Index to direct ranking.
    method : {'average', 'min', 'max', 'first', 'dense'}, default 'average'
        How to rank the group of records that have the same value (i.e. ties):
    
        * average: average rank of the group
        * min: lowest rank in the group
        * max: highest rank in the group
        * first: ranks assigned in order they appear in the array
        * dense: like 'min', but rank always increases by 1 between groups.
    
    numeric_only : bool,

#### Índices de eixos com rótulos duplicados

In [68]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [69]:
obj.index.is_unique

False

In [72]:
obj['a'] # retornar Series

a    0
a    1
dtype: int64

In [73]:
obj['c']  # retorna Escalar

4

In [75]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])
df

0         1         2
a  3.239279  0.511709  0.058176
a  0.518479 -0.121292  0.960136
b  0.223178 -0.823562  1.504462
b  1.965063 -0.433256 -0.186477

In [76]:
df.loc['b']

0         1         2
b  0.223178 -0.823562  1.504462
b  1.965063 -0.433256 -0.186477

In [77]:
df[0]

a    3.239279
a    0.518479
b    0.223178
b    1.965063
Name: 0, dtype: float64

### 5.3 Métodos de Redução 
Resumindo e calculando estatísticas descritivas

In [78]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]], 
                  index=['a','b','c','d'],
                  columns=['one', 'two'])

In [79]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [80]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [81]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [83]:
df.mean(axis='columns', skipna=True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [82]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [84]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [85]:
df.idxmax()

one    b
two    d
dtype: object

In [87]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [88]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [89]:
obj = pd.Series(['a','b','c','d']*4)

In [90]:
obj

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     a
9     b
10    c
11    d
12    a
13    b
14    c
15    d
dtype: object

In [91]:
obj.describe()

count     16
unique     4
top        d
freq       4
dtype: object

In [99]:
obj.value_counts()

d    4
c    4
b    4
a    4
dtype: int64

#### Correlação e covariância

In [114]:
!pip install pandas_datareader

In [115]:
import pandas_datareader.data as web

In [108]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [126]:
all_data['AAPL'].tail()

High         Low        Open       Close       Volume  \
Date                                                                      
2021-09-13  151.419998  148.750000  150.630005  149.550003  102404300.0   
2021-09-14  151.070007  146.910004  150.350006  148.119995  109296300.0   
2021-09-15  149.440002  146.369995  148.559998  149.029999   83281300.0   
2021-09-16  148.970001  147.220001  148.440002  148.789993   68034100.0   
2021-09-17  148.820007  145.759995  148.820007  146.059998  129728700.0   

             Adj Close  
Date                    
2021-09-13  149.550003  
2021-09-14  148.119995  
2021-09-15  149.029999  
2021-09-16  148.789993  
2021-09-17  146.059998

In [127]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [128]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [129]:
returns = price.pct_change()

In [130]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-09-13  0.003893  0.008247  0.004329  0.010879
2021-09-14 -0.009562 -0.013970  0.009428 -0.000411
2021-09-15  0.006144  0.007194  0.016778  0.012552
2021-09-16 -0.001610 -0.005612  0.001312 -0.005733
2021-09-17 -0.018348 -0.008796 -0.017528 -0.020156

In [132]:
all_data.keys()

dict_keys(['AAPL', 'IBM', 'MSFT', 'GOOG'])

In [134]:
all_data['IBM'].tail()

High         Low        Open       Close     Volume  \
Date                                                                    
2021-09-13  138.990005  137.509995  138.399994  138.149994  4144100.0   
2021-09-14  138.570007  135.339996  138.399994  136.220001  4454300.0   
2021-09-15  137.800003  135.669998  136.220001  137.199997  3253900.0   
2021-09-16  137.949997  135.710007  137.279999  136.429993  2644000.0   
2021-09-17  135.919998  135.050003  135.750000  135.229996  5631300.0   

             Adj Close  
Date                    
2021-09-13  138.149994  
2021-09-14  136.220001  
2021-09-15  137.199997  
2021-09-16  136.429993  
2021-09-17  135.229996

In [135]:
price.keys()

Index(['AAPL', 'IBM', 'MSFT', 'GOOG'], dtype='object')

In [136]:
type(price)

pandas.core.frame.DataFrame

In [137]:
price.tail()

AAPL         IBM        MSFT         GOOG
Date                                                       
2021-09-13  149.550003  138.149994  296.989990  2869.300049
2021-09-14  148.119995  136.220001  299.790009  2868.120117
2021-09-15  149.029999  137.199997  304.820007  2904.120117
2021-09-16  148.789993  136.429993  305.220001  2887.469971
2021-09-17  146.059998  135.229996  299.869995  2829.270020

In [140]:
returns = price.pct_change()
returns

AAPL       IBM      MSFT      GOOG
Date                                              
2016-09-19       NaN       NaN       NaN       NaN
2016-09-20 -0.000088 -0.002712 -0.002108  0.007457
2016-09-21 -0.000176  0.006993  0.016722  0.006235
2016-09-22  0.009423  0.003729  0.001039  0.014158
2016-09-23 -0.016664 -0.007239 -0.006745 -0.000394
...              ...       ...       ...       ...
2021-09-13  0.003893  0.008247  0.004329  0.010879
2021-09-14 -0.009562 -0.013970  0.009428 -0.000411
2021-09-15  0.006144  0.007194  0.016778  0.012552
2021-09-16 -0.001610 -0.005612  0.001312 -0.005733
2021-09-17 -0.018348 -0.008796 -0.017528 -0.020156

[1259 rows x 4 columns]

In [141]:
returns['MSFT'].corr(returns['IBM'])

0.5151801989103592